<a href="https://colab.research.google.com/github/Diegocontreras-analytics/1/blob/main/Act_spractica5_DiegoContrerasIbarra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1: Matriz de Calificaciones


In [ ]:
import numpy as np
notas = np.array([
[8,7,9],
[6,5,7],
[9,8,10],
[7,6,8]
])
print("Matriz notas: ")
print(notas)

Matriz notas: 
[[ 8  7  9]
 [ 6  5  7]
 [ 9  8 10]
 [ 7  6  8]]


In [ ]:
#Calcula:
#Promedio de cada estudiante (promedio por fila).
print("-----------promedio de estudiantes---------------")
promedio0 = notas[0].mean()
print("el promedio del primer estudiante es: ",promedio0)
promedio1 = notas[1].mean()
print("el promedio del segundo estudiantes es: ",promedio1)
promedio2 = notas[2].mean()
print("el promedio del tercer estudiante es: ",promedio2)
promedio3 = notas[3].mean()
print("el promedio del cuarto estudiante es:",promedio3)
print("----------promedios de examenes-----------------")
#Promedio de cada examen (promedio por columna).
promedio_0 = notas[:, 0].mean()
print("el promedio del primer examen es: ",promedio_0)
promedio_1 = notas[:, 1].mean()
print("el promedio del segundo examen es: ",promedio_1)
promedio_2 = notas[:, 2].mean()
print("el promedio del tercer examen es: ",promedio_2)


-----------promedio de estudiantes---------------
el promedio del primer estudiante es:  8.0
el promedio del segundo estudiantes es:  6.0
el promedio del tercer estudiante es:  9.0
el promedio del cuarto estudiante es: 7.0
----------promedios de examenes-----------------
el promedio del primer examen es:  7.5
el promedio del segundo examen es:  6.5
el promedio del tercer examen es:  8.5


In [ ]:
#Extrae (slice) la columna del segundo examen.
segundo_examen = notas[:,1]
print(segundo_examen)
#Crea un nuevo arreglo con las notas mayores o iguales a 8.#
buenas_notas = notas[notas >= 8]
print(buenas_notas)

[7 5 8 6]
[ 8  9  9  8 10  8]


Ejercicio 2: Estadísticas Básicas de Ventas


In [ ]:
#Crea un arreglo ventas con los valores:[12, 15, 8, 20, 5, 18, 10].
ventas = np.array([12,15,8,20,5,18,10])

In [ ]:
#Calcula:
#Venta total (sum)
plus = np.sum(ventas)
print(plus)
#Venta promedio (mean)
prom = np.mean(ventas)
print(prom)
#Venta máxima y mínima (max, min)
maximo = np.max(ventas)
print(maximo)
minimo = np.min(ventas)
print(minimo)

88
12.571428571428571
20
5


In [ ]:
#Crea un nuevo arreglo mayores_promedio con solo las ventas mayores al promedio.
mayores_promedio = ventas[ventas > prom]
print(mayores_promedio)

[15 20 18]


In [ ]:
#Ordena el arreglo ventas de menor a mayor.
ventas_ordenadas = np.sort(ventas)
print(ventas_ordenadas)

[ 5  8 10 12 15 18 20]
